import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Muitheme from "./theme/theme";
import { Box } from "@mui/material";
import { Data } from "./custom/useDataContext";
import { LanguageSelectorContext } from "./custom/languageSelectorContext";
import TopMenu from "./ui/TopMenu";
import Notify from "./custom/Notify";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="es">
      <Muitheme>
        
        <LanguageSelectorContext>

        <Data>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Notify>
          <Box
            component="nav"
            sx={{
              position:"relative",
              display:"flex",
              alignItems:"center",
              justifyContent:"space-between",
              width:"100%",
              padding:"20px",
              zIndex:10,
            }}
          >
            <TopMenu />
          </Box>
          {children}
          </Notify>
        </body>
        </Data>
        </LanguageSelectorContext>
      </Muitheme>
    </html>
  );
}
